---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by NemoGao.
--- DateTime: 2022/4/20 9:58
---
function new_point_shps(shp_name)
    local shp = GetControl(shp_name..'.shp') or CreateShapes(shp_name,'point')
    return shp
end

function new_line_shps(shp_name)
    local shp = GetControl(shp_name..'.shp') or CreateShapes(shp_name,'line')
    return shp
end

function new_polygon_shps(shp_name)
    local shp = GetControl(shp_name..'.shp') or CreateShapes(shp_name,'polygon')
    return shp
end

function clear_shp(shps)
    for i = 1, GetRecCount(shps) do
        local shp = GetShape(shps,1)
        DelShape(shp)
    end
end